export const FINANCIAL_QUOTES = [
  { text: "Do not save what is left after spending, but spend what is left after saving.", author: "Warren Buffett" },
  { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
  { text: "Financial freedom is available to those who learn about it and work for it.", author: "Robert Kiyosaki" },
  { text: "Rich people have small TVs and big libraries, and poor people have small libraries and big TVs.", author: "Zig Ziglar" },
  { text: "It's not your salary that makes you rich, it's your spending habits.", author: "Charles A. Jaffe" },
  { text: "The stock market is a device for transferring money from the impatient to the patient.", author: "Warren Buffett" },
  { text: "Money is a terrible master but an excellent servant.", author: "P.T. Barnum" },
  { text: "You must gain control over your money or the lack of it will forever control you.", author: "Dave Ramsey" },
  { text: "A penny saved is a penny earned.", author: "Benjamin Franklin" },
  { text: "The habit of saving is itself an education; it fosters every virtue, teaches self-denial, cultivates the sense of order, trains to forethought, and so broadens the mind.", author: "T.T. Munger" },
  { text: "Never spend your money before you have earned it.", author: "Thomas Jefferson" },
  { text: "Money grows on the tree of persistence.", author: "Japanese Proverb" },
  { text: "The art is not in making money, but in keeping it.", author: "Proverb" },
  { text: "Wealth consists not in having great possessions, but in having few wants.", author: "Epictetus" },
  { text: "Every time you borrow money, you're robbing your future self.", author: "Nathan W. Morris" },
  { text: "Financial peace isn't the acquisition of stuff. It's learning to live on less than you make.", author: "Dave Ramsey" },
  { text: "Too many people spend money they haven't earned to buy things they don't want to impress people they don't like.", author: "Will Rogers" },
  { text: "The goal isn't more money. The goal is living life on your terms.", author: "Chris Brogan" },
  { text: "Money is only a tool. It will take you wherever you wish, but it will not replace you as the driver.", author: "Ayn Rand" },
  { text: "Beware of little expenses; a small leak will sink a great ship.", author: "Benjamin Franklin" },
  { text: "The best investment you can make is an investment in yourself.", author: "Warren Buffett" },
  { text: "It takes as much energy to wish as it does to plan.", author: "Eleanor Roosevelt" },
  { text: "Price is what you pay. Value is what you get.", author: "Warren Buffett" },
  { text: "Not everything that counts can be counted, and not everything that can be counted counts.", author: "Albert Einstein" },
  { text: "Earning a lot of money is not the key to prosperity. How you handle it is.", author: "Dave Ramsey" },
  { text: "Opportunity is missed by most people because it is dressed in overalls and looks like work.", author: "Thomas Edison" },
  { text: "Savings represent much more than just money. They are a stockpile of options.", author: "Michelle Singletary" },
  { text: "Make your money work for you, rather than working for your money.", author: "Unknown" },
  { text: "A budget is telling your money where to go instead of wondering where it went.", author: "Dave Ramsey" },
  { text: "The first step toward financial independence is to make saving a habit.", author: "Unknown" },
  { text: "Wealth is not about having a lot of money; it's about having a lot of options.", author: "Chris Rock" },
  { text: "If you would be wealthy, think of saving as well as getting.", author: "Benjamin Franklin" },
  { text: "To get rich, you have to be making money while you're asleep.", author: "David Bailey" },
  { text: "The quickest way to double your money is to fold it in half and put it in your back pocket.", author: "Will Rogers" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "Investing should be more like watching paint dry or watching grass grow. If you want excitement, take $800 and go to Las Vegas.", author: "Paul Samuelson" },
  { text: "October: This is one of the peculiarly dangerous months to speculate in stocks. The others are July, January, September, April, November, May, March, June, December, August, and February.", author: "Mark Twain" },
  { text: "How many millionaires do you know who have become wealthy by investing in savings accounts? I rest my case.", author: "Robert G. Allen" },
  { text: "The person who doesn't know where his next dollar is coming from usually doesn't know where his last dollar went.", author: "Unknown" },
  { text: "Money is like love; it kills slowly and painfully the one who withholds it, and enlivens the other who turns it on himself.", author: "Kahlil Gibran" },
  { text: "Wealth is the ability to fully experience life.", author: "Henry David Thoreau" },
  { text: "My favorite things in life don't cost any money.", author: "Steve Jobs" },
  { text: "An investor without investment objectives is like a traveler without a destination.", author: "Unknown" },
  { text: "Empty pockets never held anyone back. Only empty heads and empty hearts can do that.", author: "Norman Vincent Peale" },
  { text: "A man is rich in proportion to the number of things which he can afford to let alone.", author: "Henry David Thoreau" },
  { text: "Fortune sides with him who dares.", author: "Virgil" },
  { text: "Capital as such is not evil; it is its wrong use that is evil.", author: "Mahatma Gandhi" },
  { text: "Financial success comes from understanding your own strengths and weaknesses.", author: "Unknown" },
  { text: "If money is your hope for independence you will never have it. The only real security that a man will have in this world is a reserve of knowledge, experience, and ability.", author: "Henry Ford" },
  { text: "It's easier to feel a little more spiritual with a couple of bucks in your pocket.", author: "Craig Ferguson" },
  { text: "Money is a good servant but a bad master.", author: "Francis Bacon" },
  { text: "The rich invest their money and spend what is left; the poor spend their money and invest what is left.", author: "Jim Rohn" },
  { text: "In investing, what is comfortable is rarely profitable.", author: "Robert Arnott" },
  { text: "Spend less than you make, always be saving something. Put it into a tax-deferred account. Over time, it will begin to amount to something.", author: "Charlie Munger" },
  { text: "The secret to wealth is simple: Find a way to do more for others than anyone else does. Become more valuable. Do more. Give more. Be more. Serve more.", author: "Tony Robbins" },
  { text: "Don't let the fear of losing be greater than the excitement of winning.", author: "Robert Kiyosaki" },
  { text: "Formal education will make you a living; self-education will make you a fortune.", author: "Jim Rohn" },
  { text: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
  { text: "The number one problem in today's generation and economy is the lack of financial literacy.", author: "Alan Greenspan" },
  { text: "You can be young without money but you can't be old without it.", author: "Tennessee Williams" },
  { text: "Never stand begging for that which you have the power to earn.", author: "Miguel de Cervantes" },
  { text: "Before borrowing money from a friend, decide which you need most.", author: "Addison H. Hallock" },
  { text: "Budgeting has only one rule: Do not go over budget.", author: "Leslie Tayne" },
  { text: "No wealth can ever make a bad man at peace with himself.", author: "Plato" },
  { text: "Put all good eggs in one basket and then watch that basket.", author: "Andrew Carnegie" },
  { text: "The real measure of your wealth is how much you'd be worth if you lost all your money.", author: "Unknown" },
  { text: "Know what you own and know why you own it.", author: "Peter Lynch" },
  { text: "Wide diversification is only required when investors do not understand what they are doing.", author: "Warren Buffett" },
  { text: "Someone's sitting in the shade today because someone planted a tree a long time ago.", author: "Warren Buffett" },
  { text: "The most important investment you can make is in yourself.", author: "Warren Buffett" },
  { text: "I will tell you the secret to getting rich on Wall Street. You try to be greedy when others are fearful, and you try to be fearful when others are greedy.", author: "Warren Buffett" },
  { text: "Rule No.1: Never lose money. Rule No.2: Never forget rule No.1.", author: "Warren Buffett" },
  { text: "Time is more valuable than money. You can get more money, but you cannot get more time.", author: "Jim Rohn" },
  { text: "A wise person should have money in their head, but not in their heart.", author: "Jonathan Swift" },
  { text: "Money is not the only answer, but it makes a difference.", author: "Barack Obama" },
  { text: "Every day is a bank account, and time is our currency. No one is rich, no one is poor, we've got 24 hours each.", author: "Christopher Rice" },
  { text: "Money won't create success, the freedom to make it will.", author: "Nelson Mandela" },
  { text: "If you want to know what God thinks about money, just look at the people he gave it to.", author: "Dorothy Parker" },
  { text: "It's not the man who has too little, but the man who craves more, that is poor.", author: "Seneca" },
  { text: "Financial literacy is an issue that should command our attention because many Americans are not adequately organizing finances for their education, healthcare and retirement.", author: "Ron Lewis" },
  { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
  { text: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "You don't have to see the whole staircase, just take the first step.", author: "Martin Luther King Jr." },
  { text: "The greatest wealth is to live content with little.", author: "Plato" },
  { text: "There is no dignity quite so impressive, and no independence quite so important, as living within your means.", author: "Calvin Coolidge" },
  { text: "If you have trouble imagining a 20% loss in the stock market, you shouldn't be in stocks.", author: "John Bogle" },
  { text: "Courage is being scared to death but saddling up anyway.", author: "John Wayne" },
  { text: "Wealth is not about having a lot of money; it's about having a lot of options.", author: "Chris Rock" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "He who buys what he does not need steals from himself.", author: "Swedish Proverb" },
  { text: "A budget is more than just a series of numbers on a page; it is an embodiment of our values.", author: "Barack Obama" },
  { text: "Financial freedom is freedom from fear.", author: "Robert Kiyosaki" },
  { text: "One day your life will flash before your eyes. Make sure it's worth watching.", author: "Unknown" },
  { text: "Waste your money and you're only out of money, but waste your time and you've lost a part of your life.", author: "Michael LeBoeuf" },
  { text: "If you don't find a way to make money while you sleep, you will work until you die.", author: "Warren Buffett" },
  { text: "The foundation of success in life is good health: that is the substratum of fortune.", author: "P.T. Barnum" },
  { text: "By failing to prepare, you are preparing to fail.", author: "Benjamin Franklin" },
  { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
];

export function getDailyQuote(): typeof FINANCIAL_QUOTES[0] {
  const today = new Date();
  const dayOfYear = Math.floor(
    (today.getTime() - new Date(today.getFullYear(), 0, 0).getTime()) / 86400000
  );
  return FINANCIAL_QUOTES[dayOfYear % FINANCIAL_QUOTES.length];
}

export function getRandomQuote(): typeof FINANCIAL_QUOTES[0] {
  return FINANCIAL_QUOTES[Math.floor(Math.random() * FINANCIAL_QUOTES.length)];
}
